<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\RunWay.Dashboard\RunWay.Dashboard.csproj" />
    <ProjectReference Include="..\RunWay.PostgreSQL\RunWay.PostgreSQL.csproj" />
    <ProjectReference Include="..\RunWay.Runner\RunWay.Runner.csproj" />
    <ProjectReference Include="..\RunWay\RunWay.csproj" />
  </ItemGroup>
</Project>
