// <auto-generated />
using System;
using Kododo.RunWay.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kododo.RunWay.PostgreSQL.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260518101154_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("runway")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<long?>("ReccurenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("recurrence_id");

                    b.Property<int>("RetriesCount")
                        .HasColumnType("integer")
                        .HasColumnName("retries_count");

                    b.Property<long?>("RunnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("runner_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SerializedOptions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ReccurenceId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("jobs", "runway");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbJobAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Time");

                    b.ToTable("jobs_audit", "runway");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbRecurrence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("SerializedOptions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("recurrences", "runway");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbRunner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("runners", "runway");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbRunnerJobType", b =>
                {
                    b.Property<long>("RunnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("JobType")
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.HasKey("RunnerId", "JobType");

                    b.HasIndex("JobType");

                    b.ToTable("runner_job_types", "runway");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbJob", b =>
                {
                    b.HasOne("Kododo.RunWay.EntityFramework.Entities.DbRecurrence", "Recurrence")
                        .WithMany()
                        .HasForeignKey("ReccurenceId");

                    b.HasOne("Kododo.RunWay.EntityFramework.Entities.DbRunner", "Runner")
                        .WithMany("AssignedJobs")
                        .HasForeignKey("RunnerId");

                    b.Navigation("Recurrence");

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbRecurrence", b =>
                {
                    b.HasOne("Kododo.RunWay.EntityFramework.Entities.DbJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbRunnerJobType", b =>
                {
                    b.HasOne("Kododo.RunWay.EntityFramework.Entities.DbRunner", "Runner")
                        .WithMany("JobTypes")
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });

            modelBuilder.Entity("Kododo.RunWay.EntityFramework.Entities.DbRunner", b =>
                {
                    b.Navigation("AssignedJobs");

                    b.Navigation("JobTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
