<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.29" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageVersion Include="Npgsql" Version="8.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />

    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.29" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="8.0.2" />

    <PackageVersion Include="NCrontab" Version="3.4.0" />
    <PackageVersion Include="Kododo.Reiho.AspNetCore" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="FluentAssertions" Version="8.10.0" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.13.0" />
  </ItemGroup>

</Project>
